//! Built-in SAST rules for security scanning

use crate::yellow_team::types::*;
use chrono::Utc;

/// Get all built-in SAST rules
pub fn get_builtin_rules() -> Vec<SastRule> {
    let mut rules = Vec::new();

    // Add language-agnostic rules
    rules.extend(get_secrets_rules());
    
    // Add language-specific rules
    rules.extend(get_rust_rules());
    rules.extend(get_python_rules());
    rules.extend(get_javascript_rules());
    rules.extend(get_go_rules());
    rules.extend(get_java_rules());

    rules
}

/// Rules for detecting hardcoded secrets
fn get_secrets_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "SEC-001".to_string(),
            name: "Hardcoded AWS Access Key".to_string(),
            description: "AWS access key ID found in source code".to_string(),
            language: SastLanguage::Unknown, // Applies to all languages
            severity: Severity::Critical,
            category: SastCategory::HardcodedSecrets,
            pattern: r"(?i)(AKIA[0-9A-Z]{16})".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove the hardcoded AWS access key and use environment variables or AWS IAM roles instead.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-002".to_string(),
            name: "Hardcoded AWS Secret Key".to_string(),
            description: "AWS secret access key found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::Critical,
            category: SastCategory::HardcodedSecrets,
            pattern: r#"(?i)(aws_secret_access_key|aws_secret_key)\s*[=:]\s*["'][A-Za-z0-9/+=]{40}["']"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove the hardcoded AWS secret key and use environment variables or AWS Secrets Manager.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-003".to_string(),
            name: "Hardcoded API Key".to_string(),
            description: "Generic API key pattern found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::High,
            category: SastCategory::HardcodedSecrets,
            pattern: r#"(?i)(api[_-]?key|apikey)\s*[=:]\s*["'][A-Za-z0-9]{20,}["']"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Move API keys to environment variables or a secrets management system.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-004".to_string(),
            name: "Hardcoded Password".to_string(),
            description: "Password assignment found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::High,
            category: SastCategory::HardcodedSecrets,
            pattern: r#"(?i)(password|passwd|pwd)\s*[=:]\s*["'][^"']{4,}["']"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Never hardcode passwords. Use environment variables or a secrets vault.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-005".to_string(),
            name: "Private Key".to_string(),
            description: "Private key found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::Critical,
            category: SastCategory::HardcodedSecrets,
            pattern: r"-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove private keys from source code and use secure key management.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-006".to_string(),
            name: "JWT Token".to_string(),
            description: "JWT token found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::High,
            category: SastCategory::HardcodedSecrets,
            pattern: r"eyJ[A-Za-z0-9-_]+\.eyJ[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove hardcoded JWT tokens. Generate tokens dynamically at runtime.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-007".to_string(),
            name: "GitHub Token".to_string(),
            description: "GitHub personal access token found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::Critical,
            category: SastCategory::HardcodedSecrets,
            pattern: r"ghp_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove GitHub tokens and use GitHub App tokens or environment variables.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "SEC-008".to_string(),
            name: "Slack Token".to_string(),
            description: "Slack API token found in source code".to_string(),
            language: SastLanguage::Unknown,
            severity: Severity::High,
            category: SastCategory::HardcodedSecrets,
            pattern: r"xox[baprs]-[A-Za-z0-9-]+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Remove Slack tokens and use environment variables or Slack's secure token storage.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}

/// Rust-specific SAST rules
fn get_rust_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "RUST-001".to_string(),
            name: "Unsafe Block Usage".to_string(),
            description: "Use of unsafe block which bypasses Rust's safety guarantees".to_string(),
            language: SastLanguage::Rust,
            severity: Severity::Medium,
            category: SastCategory::SecurityMisconfiguration,
            pattern: r"\bunsafe\s*\{".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-676".to_string()),
            remediation_guidance: Some("Review unsafe blocks carefully. Consider if safe alternatives exist.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "RUST-002".to_string(),
            name: "Unwrap on Option/Result".to_string(),
            description: "Use of unwrap() which can panic at runtime".to_string(),
            language: SastLanguage::Rust,
            severity: Severity::Low,
            category: SastCategory::Other,
            pattern: r"\.unwrap\(\)".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: None,
            remediation_guidance: Some("Use expect() with a meaningful message, or handle the error properly with match or ?.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "RUST-003".to_string(),
            name: "Raw Pointer Dereference".to_string(),
            description: "Dereferencing raw pointers which is unsafe".to_string(),
            language: SastLanguage::Rust,
            severity: Severity::High,
            category: SastCategory::BufferOverflow,
            pattern: r"\*\s*(const|mut)\s+\*".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-119".to_string()),
            remediation_guidance: Some("Avoid raw pointer operations. Use safe abstractions like references or smart pointers.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "RUST-004".to_string(),
            name: "Transmute Usage".to_string(),
            description: "Use of std::mem::transmute which can cause undefined behavior".to_string(),
            language: SastLanguage::Rust,
            severity: Severity::High,
            category: SastCategory::SecurityMisconfiguration,
            pattern: r"(std::mem::)?transmute".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-704".to_string()),
            remediation_guidance: Some("Avoid transmute. Use safe type conversions like From/Into traits.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}

/// Python-specific SAST rules
fn get_python_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "PY-001".to_string(),
            name: "SQL Injection".to_string(),
            description: "Potential SQL injection via string formatting".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Critical,
            category: SastCategory::SqlInjection,
            pattern: r#"(execute|executemany)\s*\([^)]*(%s|%\(|\.format|f["'])"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-89".to_string()),
            remediation_guidance: Some("Use parameterized queries instead of string formatting.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-002".to_string(),
            name: "Command Injection".to_string(),
            description: "Potential command injection via os.system or subprocess".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Critical,
            category: SastCategory::CommandInjection,
            pattern: r"(os\.system|subprocess\.call|subprocess\.Popen|subprocess\.run)\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-78".to_string()),
            remediation_guidance: Some("Use subprocess with shell=False and pass arguments as a list.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-003".to_string(),
            name: "Eval Usage".to_string(),
            description: "Use of eval() which can execute arbitrary code".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Critical,
            category: SastCategory::Injection,
            pattern: r"\beval\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-95".to_string()),
            remediation_guidance: Some("Avoid eval(). Use ast.literal_eval() for safe evaluation of literals.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-004".to_string(),
            name: "Pickle Deserialization".to_string(),
            description: "Use of pickle which can lead to arbitrary code execution".to_string(),
            language: SastLanguage::Python,
            severity: Severity::High,
            category: SastCategory::InsecureDeserialization,
            pattern: r"pickle\.(load|loads)\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-502".to_string()),
            remediation_guidance: Some("Avoid pickle for untrusted data. Use JSON or other safe serialization formats.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-005".to_string(),
            name: "Weak Cryptography - MD5".to_string(),
            description: "Use of MD5 which is cryptographically weak".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Medium,
            category: SastCategory::Cryptography,
            pattern: r"(hashlib\.md5|MD5\.new)\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-328".to_string()),
            remediation_guidance: Some("Use SHA-256 or stronger hash functions.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-006".to_string(),
            name: "Weak Cryptography - SHA1".to_string(),
            description: "Use of SHA1 which is cryptographically weak".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Medium,
            category: SastCategory::Cryptography,
            pattern: r"(hashlib\.sha1|SHA\.new)\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-328".to_string()),
            remediation_guidance: Some("Use SHA-256 or stronger hash functions.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-007".to_string(),
            name: "Path Traversal".to_string(),
            description: "Potential path traversal vulnerability".to_string(),
            language: SastLanguage::Python,
            severity: Severity::High,
            category: SastCategory::PathTraversal,
            pattern: r"open\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-22".to_string()),
            remediation_guidance: Some("Validate and sanitize file paths. Use os.path.basename() or pathlib.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "PY-008".to_string(),
            name: "Assert Statement".to_string(),
            description: "Assert statements are removed when Python is optimized".to_string(),
            language: SastLanguage::Python,
            severity: Severity::Low,
            category: SastCategory::SecurityMisconfiguration,
            pattern: r"\bassert\s+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-617".to_string()),
            remediation_guidance: Some("Don't use assert for security checks. Use explicit conditionals instead.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}

/// JavaScript/TypeScript-specific SAST rules
fn get_javascript_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "JS-001".to_string(),
            name: "Eval Usage".to_string(),
            description: "Use of eval() which can execute arbitrary code".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::Critical,
            category: SastCategory::Injection,
            pattern: r"\beval\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-95".to_string()),
            remediation_guidance: Some("Avoid eval(). Use JSON.parse() for data or Function constructor for dynamic code.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-002".to_string(),
            name: "DOM XSS - innerHTML".to_string(),
            description: "Use of innerHTML which can lead to XSS".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::High,
            category: SastCategory::Xss,
            pattern: r"\.innerHTML\s*=".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-79".to_string()),
            remediation_guidance: Some("Use textContent for text or sanitize HTML before inserting.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-003".to_string(),
            name: "DOM XSS - document.write".to_string(),
            description: "Use of document.write which can lead to XSS".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::High,
            category: SastCategory::Xss,
            pattern: r"document\.write\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-79".to_string()),
            remediation_guidance: Some("Avoid document.write. Use DOM manipulation methods instead.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-004".to_string(),
            name: "Prototype Pollution".to_string(),
            description: "Potential prototype pollution vulnerability".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::High,
            category: SastCategory::Injection,
            pattern: r"__proto__|constructor\[|prototype\[".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-1321".to_string()),
            remediation_guidance: Some("Validate object keys and avoid using user input to access object properties.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-005".to_string(),
            name: "Hardcoded Credentials".to_string(),
            description: "Hardcoded credentials in JavaScript code".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::High,
            category: SastCategory::HardcodedSecrets,
            pattern: r#"(password|secret|apiKey|api_key)\s*[:=]\s*["'][^"']+["']"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-798".to_string()),
            remediation_guidance: Some("Use environment variables or secure configuration management.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-006".to_string(),
            name: "SQL Injection".to_string(),
            description: "Potential SQL injection via string concatenation".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::Critical,
            category: SastCategory::SqlInjection,
            pattern: r#"(query|execute)\s*\([^)]*\+"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-89".to_string()),
            remediation_guidance: Some("Use parameterized queries or prepared statements.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-007".to_string(),
            name: "Insecure Randomness".to_string(),
            description: "Use of Math.random() for security-sensitive operations".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::Medium,
            category: SastCategory::Cryptography,
            pattern: r"Math\.random\s*\(\)".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-338".to_string()),
            remediation_guidance: Some("Use crypto.getRandomValues() for cryptographic operations.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JS-008".to_string(),
            name: "Command Injection".to_string(),
            description: "Potential command injection via exec".to_string(),
            language: SastLanguage::JavaScript,
            severity: Severity::Critical,
            category: SastCategory::CommandInjection,
            pattern: r"(exec|execSync|spawn|spawnSync)\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-78".to_string()),
            remediation_guidance: Some("Avoid shell execution. Use spawn with arguments array instead of exec.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}

/// Go-specific SAST rules
fn get_go_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "GO-001".to_string(),
            name: "SQL Injection".to_string(),
            description: "Potential SQL injection via string formatting".to_string(),
            language: SastLanguage::Go,
            severity: Severity::Critical,
            category: SastCategory::SqlInjection,
            pattern: r#"(Query|Exec)\s*\([^)]*fmt\.Sprintf"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-89".to_string()),
            remediation_guidance: Some("Use parameterized queries with ? placeholders.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "GO-002".to_string(),
            name: "Command Injection".to_string(),
            description: "Potential command injection via exec.Command".to_string(),
            language: SastLanguage::Go,
            severity: Severity::Critical,
            category: SastCategory::CommandInjection,
            pattern: r"exec\.Command\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-78".to_string()),
            remediation_guidance: Some("Avoid string concatenation in command arguments. Use separate arguments.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "GO-003".to_string(),
            name: "Weak Cryptography".to_string(),
            description: "Use of weak cryptographic algorithms".to_string(),
            language: SastLanguage::Go,
            severity: Severity::Medium,
            category: SastCategory::Cryptography,
            pattern: r"(crypto/md5|crypto/sha1|crypto/des)".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-328".to_string()),
            remediation_guidance: Some("Use crypto/sha256 or stronger algorithms.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "GO-004".to_string(),
            name: "Insecure TLS Configuration".to_string(),
            description: "TLS configuration with InsecureSkipVerify enabled".to_string(),
            language: SastLanguage::Go,
            severity: Severity::High,
            category: SastCategory::SecurityMisconfiguration,
            pattern: r"InsecureSkipVerify\s*:\s*true".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-295".to_string()),
            remediation_guidance: Some("Never disable TLS certificate verification in production.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "GO-005".to_string(),
            name: "Path Traversal".to_string(),
            description: "Potential path traversal vulnerability".to_string(),
            language: SastLanguage::Go,
            severity: Severity::High,
            category: SastCategory::PathTraversal,
            pattern: r"(os\.Open|ioutil\.ReadFile)\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-22".to_string()),
            remediation_guidance: Some("Use filepath.Clean() and validate paths against a base directory.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}

/// Java-specific SAST rules
fn get_java_rules() -> Vec<SastRule> {
    vec![
        SastRule {
            id: "JAVA-001".to_string(),
            name: "SQL Injection".to_string(),
            description: "Potential SQL injection via string concatenation".to_string(),
            language: SastLanguage::Java,
            severity: Severity::Critical,
            category: SastCategory::SqlInjection,
            pattern: r#"(executeQuery|executeUpdate|execute)\s*\([^)]*\+"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-89".to_string()),
            remediation_guidance: Some("Use PreparedStatement with parameterized queries.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-002".to_string(),
            name: "Command Injection".to_string(),
            description: "Potential command injection via Runtime.exec".to_string(),
            language: SastLanguage::Java,
            severity: Severity::Critical,
            category: SastCategory::CommandInjection,
            pattern: r"Runtime\.getRuntime\(\)\.exec\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-78".to_string()),
            remediation_guidance: Some("Use ProcessBuilder with separate command and arguments.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-003".to_string(),
            name: "XXE Vulnerability".to_string(),
            description: "XML parsing without disabling external entities".to_string(),
            language: SastLanguage::Java,
            severity: Severity::High,
            category: SastCategory::Xxe,
            pattern: r"(DocumentBuilderFactory|SAXParserFactory|XMLInputFactory)\.newInstance\(\)".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-611".to_string()),
            remediation_guidance: Some("Disable external entities by setting appropriate features on the parser factory.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-004".to_string(),
            name: "Insecure Deserialization".to_string(),
            description: "Use of ObjectInputStream which can lead to RCE".to_string(),
            language: SastLanguage::Java,
            severity: Severity::Critical,
            category: SastCategory::InsecureDeserialization,
            pattern: r"ObjectInputStream\s*\(".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-502".to_string()),
            remediation_guidance: Some("Avoid Java serialization. Use JSON or implement a whitelist filter.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-005".to_string(),
            name: "Weak Cryptography".to_string(),
            description: "Use of weak cryptographic algorithms".to_string(),
            language: SastLanguage::Java,
            severity: Severity::Medium,
            category: SastCategory::Cryptography,
            pattern: r#"(MessageDigest|Cipher)\.getInstance\s*\(\s*["'](MD5|SHA1|DES|RC4)["']"#.to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-328".to_string()),
            remediation_guidance: Some("Use SHA-256, AES-GCM, or other strong algorithms.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-006".to_string(),
            name: "Path Traversal".to_string(),
            description: "Potential path traversal vulnerability".to_string(),
            language: SastLanguage::Java,
            severity: Severity::High,
            category: SastCategory::PathTraversal,
            pattern: r"new File\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-22".to_string()),
            remediation_guidance: Some("Validate file paths and use canonical paths for comparison.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
        SastRule {
            id: "JAVA-007".to_string(),
            name: "LDAP Injection".to_string(),
            description: "Potential LDAP injection vulnerability".to_string(),
            language: SastLanguage::Java,
            severity: Severity::High,
            category: SastCategory::Injection,
            pattern: r"(search|lookup)\s*\([^)]*\+".to_string(),
            pattern_type: PatternType::Regex,
            cwe_id: Some("CWE-90".to_string()),
            remediation_guidance: Some("Use parameterized LDAP queries or escape special characters.".to_string()),
            enabled: true,
            custom: false,
            created_by: None,
            created_at: Utc::now(),
        },
    ]
}
