pub mod ad_assessment;
pub mod admin;
pub mod analytics;
pub mod api_keys;
pub mod api_security;
pub mod assets;
pub mod attack_paths;
pub mod auth;
pub mod cloud;
pub mod credential_audit;
pub mod compare;
pub mod compliance;
pub mod crm;
pub mod dashboard;
pub mod dns;
pub mod finding_templates;
pub mod jira;
pub mod manual_compliance;
pub mod methodology;
pub mod mfa;
pub mod notifications;
pub mod portal;
pub mod privacy;
pub mod reports;
pub mod scan_presets;
pub mod scans;
pub mod scheduled_scans;
pub mod siem;
pub mod target_groups;
pub mod templates;
pub mod threat_intel;
pub mod topology;
pub mod vulnerabilities;
pub mod vpn;
pub mod webapp;

#[cfg(test)]
mod tests;
