//! PCI DSS 4.0 Compliance Framework
//!
//! Payment Card Industry Data Security Standard version 4.0
//! Controls for organizations handling payment card data.

use crate::compliance::types::{
    ComplianceControl, ComplianceFramework, ControlPriority,
};

/// Total number of PCI DSS 4.0 controls
pub const CONTROL_COUNT: usize = 64; // Key technical controls

/// Get all PCI DSS 4.0 controls
pub fn get_controls() -> Vec<ComplianceControl> {
    vec![
        // Requirement 1: Install and Maintain Network Security Controls
        ComplianceControl {
            id: "pci-dss-1.1.1".to_string(),
            control_id: "1.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Network security controls are defined and understood".to_string(),
            description: "All security policies and operational procedures for network security controls are documented, in use, and known to all affected parties.".to_string(),
            category: "Network Security".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SC-7".to_string(), "CIS-9.1".to_string()],
            remediation_guidance: Some("Document all firewall rules, network diagrams, and security procedures. Ensure staff training on network security policies.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-1.2.1".to_string(),
            control_id: "1.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Network security controls restrict traffic".to_string(),
            description: "Configuration standards for NSCs are defined, implemented, and maintained.".to_string(),
            category: "Network Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-7".to_string()],
            remediation_guidance: Some("Implement deny-all, permit-by-exception firewall rules. Document all allowed traffic flows.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-1.3.1".to_string(),
            control_id: "1.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Inbound traffic to CDE is restricted".to_string(),
            description: "Inbound traffic to the cardholder data environment is restricted to only necessary traffic.".to_string(),
            category: "Network Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-7".to_string(), "CIS-9.2".to_string()],
            remediation_guidance: Some("Configure firewalls to restrict inbound traffic to CDE. Only allow required protocols and ports.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-1.3.2".to_string(),
            control_id: "1.3.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Outbound traffic from CDE is restricted".to_string(),
            description: "Outbound traffic from the cardholder data environment is restricted to only necessary traffic.".to_string(),
            category: "Network Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-7".to_string()],
            remediation_guidance: Some("Implement egress filtering. Restrict outbound connections to approved destinations.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-1.4.1".to_string(),
            control_id: "1.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "NSCs between wireless and CDE".to_string(),
            description: "Network security controls are implemented between wireless networks and the CDE.".to_string(),
            category: "Network Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-7".to_string(), "CIS-15.1".to_string()],
            remediation_guidance: Some("Isolate wireless networks from CDE with firewalls. Implement strict access controls.".to_string()),
        },

        // Requirement 2: Apply Secure Configurations
        ComplianceControl {
            id: "pci-dss-2.1.1".to_string(),
            control_id: "2.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Vendor-supplied defaults changed".to_string(),
            description: "All vendor-supplied default accounts are removed, disabled, or changed before installing systems on the network.".to_string(),
            category: "Secure Configuration".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-CM-6".to_string(), "CIS-4.1".to_string()],
            remediation_guidance: Some("Change all default passwords. Disable or remove unnecessary default accounts.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-2.2.1".to_string(),
            control_id: "2.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Configuration standards developed".to_string(),
            description: "Configuration standards are developed, implemented, and maintained for system components.".to_string(),
            category: "Secure Configuration".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-CM-2".to_string(), "CIS-4.1".to_string()],
            remediation_guidance: Some("Develop hardening standards based on CIS Benchmarks or vendor guidance.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-2.2.4".to_string(),
            control_id: "2.2.4".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Unnecessary services disabled".to_string(),
            description: "Only necessary services, protocols, daemons, and functions are enabled.".to_string(),
            category: "Secure Configuration".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-CM-7".to_string(), "CIS-4.8".to_string()],
            remediation_guidance: Some("Disable all unnecessary services. Remove or disable unused network protocols.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-2.2.5".to_string(),
            control_id: "2.2.5".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Insecure services secured".to_string(),
            description: "If insecure services are present, additional security features are implemented.".to_string(),
            category: "Secure Configuration".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-8".to_string()],
            remediation_guidance: Some("Replace insecure protocols (Telnet, FTP) with secure alternatives (SSH, SFTP).".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-2.2.7".to_string(),
            control_id: "2.2.7".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Non-console admin encrypted".to_string(),
            description: "All non-console administrative access is encrypted with strong cryptography.".to_string(),
            category: "Secure Configuration".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-8".to_string(), "CIS-5.2".to_string()],
            remediation_guidance: Some("Use SSH, HTTPS, or VPN for all remote administration. Disable unencrypted protocols.".to_string()),
        },

        // Requirement 3: Protect Stored Account Data
        ComplianceControl {
            id: "pci-dss-3.4.1".to_string(),
            control_id: "3.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "PAN rendered unreadable".to_string(),
            description: "PAN is rendered unreadable anywhere it is stored using strong cryptography.".to_string(),
            category: "Data Protection".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SC-28".to_string(), "HIPAA-164.312(a)(2)(iv)".to_string()],
            remediation_guidance: Some("Implement AES-256 encryption for stored PAN data. Use tokenization where possible.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-3.5.1".to_string(),
            control_id: "3.5.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Cryptographic keys protected".to_string(),
            description: "A documented description of the cryptographic architecture is maintained.".to_string(),
            category: "Data Protection".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SC-12".to_string()],
            remediation_guidance: Some("Document key management procedures. Use HSMs for key storage where possible.".to_string()),
        },

        // Requirement 4: Protect Cardholder Data in Transit
        ComplianceControl {
            id: "pci-dss-4.1.1".to_string(),
            control_id: "4.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Strong cryptography in transit".to_string(),
            description: "Strong cryptography and security protocols are defined and documented.".to_string(),
            category: "Transmission Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-8".to_string(), "HIPAA-164.312(e)(1)".to_string()],
            remediation_guidance: Some("Use TLS 1.2 or higher. Disable SSL and older TLS versions.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-4.2.1".to_string(),
            control_id: "4.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "PAN secured in transmission".to_string(),
            description: "PAN is secured with strong cryptography whenever it is transmitted over open, public networks.".to_string(),
            category: "Transmission Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SC-8".to_string()],
            remediation_guidance: Some("Encrypt all PAN transmissions with TLS 1.2+. Never send PAN over unencrypted channels.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-4.2.2".to_string(),
            control_id: "4.2.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "PAN secured in messaging".to_string(),
            description: "PAN is secured with strong cryptography whenever sent via end-user messaging technologies.".to_string(),
            category: "Transmission Security".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SC-8".to_string()],
            remediation_guidance: Some("Never transmit PAN via email, chat, or SMS without encryption.".to_string()),
        },

        // Requirement 5: Protect Systems and Networks from Malware
        ComplianceControl {
            id: "pci-dss-5.2.1".to_string(),
            control_id: "5.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Anti-malware deployed".to_string(),
            description: "An anti-malware solution is deployed on all system components.".to_string(),
            category: "Malware Protection".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SI-3".to_string(), "CIS-10.1".to_string()],
            remediation_guidance: Some("Deploy anti-malware on all Windows systems and servers. Consider EDR solutions.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-5.2.3".to_string(),
            control_id: "5.2.3".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Anti-malware mechanisms active".to_string(),
            description: "Anti-malware mechanisms are actively running and cannot be disabled.".to_string(),
            category: "Malware Protection".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SI-3".to_string()],
            remediation_guidance: Some("Configure anti-malware to prevent user disabling. Implement tamper protection.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-5.3.1".to_string(),
            control_id: "5.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Anti-malware kept current".to_string(),
            description: "Anti-malware mechanisms and definitions are kept current.".to_string(),
            category: "Malware Protection".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SI-3".to_string()],
            remediation_guidance: Some("Enable automatic definition updates. Monitor for update failures.".to_string()),
        },

        // Requirement 6: Develop and Maintain Secure Systems
        ComplianceControl {
            id: "pci-dss-6.2.1".to_string(),
            control_id: "6.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Secure development practices".to_string(),
            description: "Bespoke and custom software is developed securely.".to_string(),
            category: "Secure Development".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SA-11".to_string()],
            remediation_guidance: Some("Implement secure coding standards. Train developers on OWASP Top 10.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-6.3.1".to_string(),
            control_id: "6.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Security vulnerabilities identified".to_string(),
            description: "Security vulnerabilities are identified and addressed.".to_string(),
            category: "Vulnerability Management".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-RA-5".to_string(), "CIS-7.1".to_string()],
            remediation_guidance: Some("Subscribe to vendor security advisories. Monitor CVE databases.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-6.3.3".to_string(),
            control_id: "6.3.3".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Critical patches installed".to_string(),
            description: "Security patches are installed within one month of release.".to_string(),
            category: "Vulnerability Management".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SI-2".to_string(), "CIS-7.3".to_string()],
            remediation_guidance: Some("Implement patch management process. Deploy critical patches within 30 days.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-6.4.1".to_string(),
            control_id: "6.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Public-facing web apps protected".to_string(),
            description: "Public-facing web applications are protected against attacks.".to_string(),
            category: "Application Security".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SI-10".to_string()],
            remediation_guidance: Some("Deploy WAF for public web apps. Conduct regular penetration testing.".to_string()),
        },

        // Requirement 7: Restrict Access to System Components
        ComplianceControl {
            id: "pci-dss-7.1.1".to_string(),
            control_id: "7.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Access limited to need-to-know".to_string(),
            description: "Policies and processes are defined for restricting access to system components.".to_string(),
            category: "Access Control".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AC-1".to_string(), "HIPAA-164.312(a)(1)".to_string()],
            remediation_guidance: Some("Implement role-based access control. Document access requirements per role.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-7.2.1".to_string(),
            control_id: "7.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Access control model established".to_string(),
            description: "An access control model is defined and includes granting access based on job classification.".to_string(),
            category: "Access Control".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AC-2".to_string()],
            remediation_guidance: Some("Define access levels per job function. Implement least privilege principle.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-7.2.5".to_string(),
            control_id: "7.2.5".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Access assigned with least privilege".to_string(),
            description: "All access assigned is based on the principle of least privilege.".to_string(),
            category: "Access Control".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-AC-6".to_string(), "CIS-5.4".to_string()],
            remediation_guidance: Some("Review and minimize user privileges. Remove unnecessary admin rights.".to_string()),
        },

        // Requirement 8: Identify Users and Authenticate Access
        ComplianceControl {
            id: "pci-dss-8.2.1".to_string(),
            control_id: "8.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Unique IDs assigned".to_string(),
            description: "All users are assigned a unique ID before access is allowed.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-2".to_string(), "HIPAA-164.312(d)".to_string()],
            remediation_guidance: Some("Eliminate shared accounts. Assign unique IDs to all users.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.2.2".to_string(),
            control_id: "8.2.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Shared accounts managed".to_string(),
            description: "Group, shared, or generic accounts are only used when necessary.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-2".to_string()],
            remediation_guidance: Some("Minimize shared accounts. Document business justification for any shared accounts.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.3.1".to_string(),
            control_id: "8.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Strong authentication for users".to_string(),
            description: "User identity is verified with strong authentication factors.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-2".to_string(), "CIS-5.2".to_string()],
            remediation_guidance: Some("Implement multi-factor authentication. Enforce strong password policies.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.3.6".to_string(),
            control_id: "8.3.6".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Password complexity enforced".to_string(),
            description: "Passwords meet minimum complexity requirements.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-5".to_string(), "CIS-5.2".to_string()],
            remediation_guidance: Some("Require passwords of 12+ characters with complexity. Consider passphrases.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.3.7".to_string(),
            control_id: "8.3.7".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Password history enforced".to_string(),
            description: "Individuals cannot submit a new password that is the same as any of the last four passwords.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::Medium,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-5".to_string()],
            remediation_guidance: Some("Configure password history to remember at least 4 passwords.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.4.1".to_string(),
            control_id: "8.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "MFA for CDE access".to_string(),
            description: "Multi-factor authentication is implemented for all access into the CDE.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-2(1)".to_string()],
            remediation_guidance: Some("Deploy MFA for all CDE access. Use hardware tokens or authenticator apps.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.4.2".to_string(),
            control_id: "8.4.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "MFA for remote access".to_string(),
            description: "Multi-factor authentication is implemented for all remote network access.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-IA-2(1)".to_string(), "CIS-6.5".to_string()],
            remediation_guidance: Some("Require MFA for VPN and remote desktop access. No exceptions.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.5.1".to_string(),
            control_id: "8.5.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "MFA systems properly configured".to_string(),
            description: "MFA systems are implemented to prevent misuse.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-IA-2(1)".to_string()],
            remediation_guidance: Some("MFA should require both factors for each authentication attempt.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-8.6.1".to_string(),
            control_id: "8.6.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Interactive login for service accounts restricted".to_string(),
            description: "System or application accounts cannot be used for interactive login.".to_string(),
            category: "Authentication".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-AC-6".to_string()],
            remediation_guidance: Some("Disable interactive login for service accounts. Use managed service accounts.".to_string()),
        },

        // Requirement 9: Restrict Physical Access
        ComplianceControl {
            id: "pci-dss-9.1.1".to_string(),
            control_id: "9.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Physical security controls documented".to_string(),
            description: "Physical security policies and procedures are defined and implemented.".to_string(),
            category: "Physical Security".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-PE-1".to_string()],
            remediation_guidance: Some("Document physical access procedures. Implement badge access systems.".to_string()),
        },

        // Requirement 10: Log and Monitor All Access
        ComplianceControl {
            id: "pci-dss-10.1.1".to_string(),
            control_id: "10.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Audit logs defined".to_string(),
            description: "Audit log policies and procedures are defined and implemented.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AU-1".to_string(), "HIPAA-164.312(b)".to_string()],
            remediation_guidance: Some("Document logging requirements. Define retention periods.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.2.1".to_string(),
            control_id: "10.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Audit logs enabled".to_string(),
            description: "Audit logs are enabled and active for all system components in the CDE.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-AU-2".to_string(), "CIS-8.2".to_string()],
            remediation_guidance: Some("Enable logging on all CDE systems. Configure centralized log collection.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.2.1.1".to_string(),
            control_id: "10.2.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "User access logged".to_string(),
            description: "All individual user access to cardholder data is logged.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: Some("pci-dss-10.2.1".to_string()),
            cross_references: vec!["NIST-AU-3".to_string()],
            remediation_guidance: Some("Log all access attempts to cardholder data. Include user ID and timestamp.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.2.1.2".to_string(),
            control_id: "10.2.1.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Admin actions logged".to_string(),
            description: "All actions taken by any individual with root or administrative privileges are logged.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: Some("pci-dss-10.2.1".to_string()),
            cross_references: vec!["NIST-AU-3".to_string()],
            remediation_guidance: Some("Enable command logging for admin sessions. Monitor privileged activity.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.2.1.5".to_string(),
            control_id: "10.2.1.5".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Access changes logged".to_string(),
            description: "All changes to identification and authentication credentials are logged.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: Some("pci-dss-10.2.1".to_string()),
            cross_references: vec!["NIST-AU-3".to_string()],
            remediation_guidance: Some("Log password changes, account creation, and privilege modifications.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.3.1".to_string(),
            control_id: "10.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Log entries contain required elements".to_string(),
            description: "Audit log entries include all required information.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-AU-3".to_string()],
            remediation_guidance: Some("Include user ID, event type, date/time, success/failure, origin, and affected resource.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.4.1".to_string(),
            control_id: "10.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Logs reviewed daily".to_string(),
            description: "Audit logs are reviewed at least once daily.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AU-6".to_string()],
            remediation_guidance: Some("Implement SIEM with automated alerting. Define daily review procedures.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.5.1".to_string(),
            control_id: "10.5.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Logs retained for one year".to_string(),
            description: "Audit log history is retained for at least 12 months.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AU-11".to_string()],
            remediation_guidance: Some("Configure log retention for 12 months minimum. 3 months immediately accessible.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.6.1".to_string(),
            control_id: "10.6.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Time synchronization".to_string(),
            description: "Time-synchronization technology is implemented and kept current.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-AU-8".to_string(), "CIS-8.4".to_string()],
            remediation_guidance: Some("Configure NTP on all systems. Synchronize to authoritative time source.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-10.7.1".to_string(),
            control_id: "10.7.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Security control failures detected".to_string(),
            description: "Failures of critical security control systems are detected and responded to.".to_string(),
            category: "Logging and Monitoring".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SI-4".to_string()],
            remediation_guidance: Some("Monitor security controls for failures. Alert on firewall, IDS, AV failures.".to_string()),
        },

        // Requirement 11: Test Security of Systems and Networks
        ComplianceControl {
            id: "pci-dss-11.2.1".to_string(),
            control_id: "11.2.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Wireless access points detected".to_string(),
            description: "Processes are implemented to detect and identify authorized and unauthorized wireless access points.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-RA-5".to_string()],
            remediation_guidance: Some("Perform quarterly wireless scans. Maintain inventory of authorized APs.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-11.3.1".to_string(),
            control_id: "11.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Internal vulnerability scans".to_string(),
            description: "Internal vulnerability scans are performed at least quarterly.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-RA-5".to_string(), "CIS-7.1".to_string()],
            remediation_guidance: Some("Perform quarterly internal scans. Remediate high-risk vulnerabilities.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-11.3.2".to_string(),
            control_id: "11.3.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "External vulnerability scans".to_string(),
            description: "External vulnerability scans are performed at least quarterly by an ASV.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-RA-5".to_string()],
            remediation_guidance: Some("Engage ASV for quarterly external scans. Achieve passing scan status.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-11.4.1".to_string(),
            control_id: "11.4.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Penetration testing performed".to_string(),
            description: "External and internal penetration testing is performed at least annually.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-CA-8".to_string()],
            remediation_guidance: Some("Conduct annual pen tests. Include network and application testing.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-11.5.1".to_string(),
            control_id: "11.5.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Intrusion detection/prevention".to_string(),
            description: "Intrusion-detection and/or intrusion-prevention techniques are used to detect and/or prevent intrusions.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SI-4".to_string(), "CIS-13.3".to_string()],
            remediation_guidance: Some("Deploy IDS/IPS at network perimeter and critical segments. Monitor alerts.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-11.5.2".to_string(),
            control_id: "11.5.2".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Change detection deployed".to_string(),
            description: "A change-detection mechanism is deployed to alert personnel to unauthorized modification of critical files.".to_string(),
            category: "Security Testing".to_string(),
            priority: ControlPriority::High,
            automated_check: true,
            parent_id: None,
            cross_references: vec!["NIST-SI-7".to_string(), "CIS-11.5".to_string()],
            remediation_guidance: Some("Deploy file integrity monitoring (FIM) on critical system files.".to_string()),
        },

        // Requirement 12: Support Information Security with Policies
        ComplianceControl {
            id: "pci-dss-12.1.1".to_string(),
            control_id: "12.1.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Security policy established".to_string(),
            description: "An overall information security policy is established, published, maintained, and disseminated.".to_string(),
            category: "Security Policy".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-PL-1".to_string()],
            remediation_guidance: Some("Document comprehensive security policy. Review and update annually.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-12.3.1".to_string(),
            control_id: "12.3.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Acceptable use policies".to_string(),
            description: "Acceptable use policies for end-user technologies are documented and implemented.".to_string(),
            category: "Security Policy".to_string(),
            priority: ControlPriority::Medium,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-PL-4".to_string()],
            remediation_guidance: Some("Document acceptable use policies. Obtain user acknowledgment.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-12.6.1".to_string(),
            control_id: "12.6.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Security awareness program".to_string(),
            description: "A formal security awareness program is implemented.".to_string(),
            category: "Security Awareness".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-AT-2".to_string(), "HIPAA-164.308(a)(5)".to_string()],
            remediation_guidance: Some("Implement annual security awareness training. Track completion.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-12.8.1".to_string(),
            control_id: "12.8.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Service provider list maintained".to_string(),
            description: "A list of service providers with whom account data is shared is maintained.".to_string(),
            category: "Third-Party Management".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-SA-9".to_string()],
            remediation_guidance: Some("Maintain inventory of service providers. Document data shared.".to_string()),
        },
        ComplianceControl {
            id: "pci-dss-12.10.1".to_string(),
            control_id: "12.10.1".to_string(),
            framework: ComplianceFramework::PciDss4,
            title: "Incident response plan".to_string(),
            description: "An incident response plan exists and is ready to be activated immediately.".to_string(),
            category: "Incident Response".to_string(),
            priority: ControlPriority::High,
            automated_check: false,
            parent_id: None,
            cross_references: vec!["NIST-IR-1".to_string(), "HIPAA-164.308(a)(6)".to_string()],
            remediation_guidance: Some("Document incident response procedures. Include escalation contacts.".to_string()),
        },
    ]
}

/// Map vulnerability patterns to PCI DSS controls
pub fn map_vulnerability(
    vuln_title: &str,
    cve_id: Option<&str>,
    port: Option<u16>,
    _service: Option<&str>,
) -> Vec<(String, crate::types::Severity)> {
    use crate::types::Severity;
    let mut mappings = Vec::new();
    let title_lower = vuln_title.to_lowercase();

    // SMB vulnerabilities
    if title_lower.contains("smb") || cve_id.map_or(false, |c| c.contains("MS17")) {
        mappings.push(("pci-dss-11.3.1".to_string(), Severity::High)); // Internal vuln scans
        mappings.push(("pci-dss-6.3.1".to_string(), Severity::High));  // Security vulnerabilities identified
    }

    // TLS/SSL vulnerabilities
    if title_lower.contains("tls") || title_lower.contains("ssl") || title_lower.contains("heartbleed") {
        mappings.push(("pci-dss-4.1.1".to_string(), Severity::High)); // Strong cryptography
        mappings.push(("pci-dss-4.2.1".to_string(), Severity::High)); // PAN secured in transmission
        mappings.push(("pci-dss-2.2.7".to_string(), Severity::Medium)); // Non-console admin encrypted
    }

    // Weak authentication
    if title_lower.contains("default password") || title_lower.contains("weak password") {
        mappings.push(("pci-dss-2.1.1".to_string(), Severity::Critical)); // Vendor defaults changed
        mappings.push(("pci-dss-8.3.6".to_string(), Severity::High)); // Password complexity
    }

    // Unencrypted protocols
    if title_lower.contains("telnet") || title_lower.contains("ftp") || title_lower.contains("unencrypted") {
        mappings.push(("pci-dss-2.2.5".to_string(), Severity::High)); // Insecure services secured
        mappings.push(("pci-dss-2.2.7".to_string(), Severity::Medium)); // Non-console admin encrypted
    }

    // Missing patches
    if title_lower.contains("patch") || title_lower.contains("update") || title_lower.contains("outdated") {
        mappings.push(("pci-dss-6.3.3".to_string(), Severity::High)); // Critical patches installed
    }

    // RDP exposure
    if port == Some(3389) || title_lower.contains("rdp") {
        mappings.push(("pci-dss-8.4.2".to_string(), Severity::High)); // MFA for remote access
        mappings.push(("pci-dss-2.2.7".to_string(), Severity::Medium)); // Non-console admin encrypted
    }

    // Database exposure
    if port == Some(1433) || port == Some(3306) || port == Some(5432) || port == Some(27017) {
        mappings.push(("pci-dss-1.3.1".to_string(), Severity::High)); // Inbound traffic restricted
        mappings.push(("pci-dss-7.2.5".to_string(), Severity::Medium)); // Least privilege
    }

    // Web vulnerabilities
    if title_lower.contains("xss") || title_lower.contains("sql injection") || title_lower.contains("csrf") {
        mappings.push(("pci-dss-6.4.1".to_string(), Severity::Critical)); // Public-facing web apps protected
        mappings.push(("pci-dss-6.2.1".to_string(), Severity::High)); // Secure development
    }

    mappings
}
